apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice-deployment
  labels:
    app: inventoryservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
      - name: inventoryservice
        image: nivakaran/inventoryservice:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice
spec:
  selector:
    app: inventoryservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
