apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacyservice-deployment
  labels:
    app: pharmacyservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pharmacyservice
  template:
    metadata:
      labels:
        app: pharmacyservice
    spec:
      containers:
      - name: pharmacyservice
        image: nivakaran/pharmacyservice:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: pharmacyservice
spec:
  selector:
    app: pharmacyservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
