apiVersion: apps/v1
kind: Deployment
metadata:
  name: staffservice-deployment
  labels:
    app: staffservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staffservice
  template:
    metadata:
      labels:
        app: staffservice
    spec:
      containers:
      - name: staffservice
        image: nivakaran/staffservice:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: staffservice
spec:
  selector:
    app: staffservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
